### ISSUE TITLE
Narrowing error on master with -Wc++11-narrowing

### ISSUE THREAD

**Issue by aianus** [tplgy/cppcodec#53]
```
/Users/aianus/src/cryptopals/vendor/cppcodec/cppcodec/detail/stream_codec.hpp:244:65: error: constant expression evaluates to 4294967040 which cannot be narrowed to type 'cppcodec::detail::alphabet_index_t' (aka 'unsigned short') [-Wc++11-narrowing]
    static constexpr const alphabet_index_t stop_character_mask{~0xFFu};
```

The expression ~0xFFu is evaluated to a 32-bit integer on my system and alphabet_index_t is 16 bits.

Reverting [this commit](https://github.com/tplgy/cppcodec/commit/be82262267c1e089f933333617885eab23e2f1df) fixes the problem but I am not sure how to fix the problem and maintain the MSVC build time optimization

**Comment by jpetso** [comment]
I believe this has been fixed by #54. Please reopen if you continue to run into any issues.
