### ISSUE TITLE
Exclude example and tool

### ISSUE THREAD

**Issue by ghuser404** [tplgy/cppcodec#61]
Add CMake options to exclude example and tool.

**Comment by jpetso** [comment]
Related to issue #60, where I imply that the CMakeLists.txt are only meant for internal usage (tests, examples, tools) and not meant to be included by another CMake directory.

I can see how excluding examples can be helpful if one just wants the tools - maybe this should be lumped together with the BUILD_TESTING flag?

I can't see how excluding the tools directory would make sense in any use case. They're good for testing and good for distribution, and people who just use the header-only library would ignore it by simply adding the root as include directory, without adding the project's CMakeLists.txt as a dependency.

**Comment by ghuser404** [comment]
I can only say from point of view of a user who would be including the library as a subproject (with `target_link_libraries`). If that is not an option with this library, according to your answer in #60, then there is no need for this issue.
